version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'
        volumes:
            - ./src:/var/www/html
            
    databaseBlog:
        image: mariadb
        restart: always
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - data:/var/lib/mysql
        environment:
            MARIADB_DATABASE: data
            MARIADB_ROOT_PASSWORD: password    
    adminer:
        image: adminer
        restart: always
        ports:
            - '1333:8080'



volumes:
    data: